services:
  mongodb:
    image: mongo:7
    container_name: traffic-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: traffic-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/userssss
      - JWT_SECRET=control-center-secret-key-998877
    depends_on:
      mongodb:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: traffic-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo_data:
